### ISSUE TITLE
opendistro-es: timed out waiting for the condition exit status

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#441]
On a brand new cluster, I get this:

```shellSession
$ ./bin/ck8s apply sc
[...]
Release "opendistro-es" does not exist. Installing it now.


UPDATED RELEASES:
NAME                    CHART                                        VERSION
cluster-admin-rbac      charts/cluster-admin-rbac                      0.1.0
fluentd-configmap       charts/fluentd-configmap                       0.1.0
node-local-dns          charts/node-local-dns                          0.1.0
wc-reader               charts/prometheus-instance                     0.1.0
blackbox                charts/blackbox                                0.1.0
calico-accountant       charts/calico-accountant                       0.1.0
grafana-ops             charts/grafana-ops                             0.2.0
s3-exporter             charts/s3-exporter                             0.1.0
influxdb                elastisys/influxdb                            4.8.12
velero                  vmware-tanzu/velero                           2.15.0
metrics-server          stable/metrics-server                         2.10.0
cert-manager            jetstack/cert-manager                         v1.1.0
ingress-nginx           ingress-nginx/ingress-nginx                   2.10.0
issuers                 charts/issuers                                      
user-grafana            grafana/grafana                               6.1.11
fluentd                 bitnami/fluentd                                2.4.0
dex                     stable/dex                                    2.15.2
kube-prometheus-stack   prometheus-community/kube-prometheus-stack    12.8.0


FAILED RELEASES:
NAME
opendistro-es
in ./01-applications.yaml: failed processing release opendistro-es: command "/home/cklein/bin/helm" exited with non-zero status:

PATH:
  /home/cklein/bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: opendistro-es (13 bytes)
  5: elastisys/opendistro-es (23 bytes)
  6: --version (9 bytes)
  7: 1.12.1 (6 bytes)
  8: --timeout (9 bytes)
  9: 600s (4 bytes)
  10: --namespace (11 bytes)
  11: elastic-system (14 bytes)
  12: --values (8 bytes)
  13: /tmp/helmfile820522729/elastic-system-opendistro-es-values-85c4dbb747 (69 bytes)
  14: --history-max (13 bytes)
  15: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: failed post-install: timed out waiting for the condition

COMBINED OUTPUT:
  Release "opendistro-es" does not exist. Installing it now.
  Error: failed post-install: timed out waiting for the condition
exit status 1
```

Delete, re-apply didn't help:
```shellSession
$ ./compliantkubernetes-apps/bin/ck8s ops kubectl sc delete ns elastic-system
namespace "elastic-system" deleted
```

I found the following errors:

```
$ ./compliantkubernetes-apps/bin/ck8s ops kubectl sc -n elastic-system logs opendistro-es-master-0 -c install-object-storage-plugin
-> Installing repository-s3
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.elasticsearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:418)
	at org.elasticsearch.plugins.InstallPluginCommand.getElasticUrl(InstallPluginCommand.java:374)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:305)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:251)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.15.0

**Comment by cristiklein** [comment]
Closing. Root cause is here: https://github.com/elastisys/compliantkubernetes-kubespray/issues/80
