### ISSUE TITLE
Starboard: error getting resource - causing panic?

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#573]
**Describe the bug**
Starbord operator crashlooping due to it not being unable to find some resources (i think).

```
{"level":"error","ts":1629697812.33809,"logger":"controller-runtime.manager.controller.statefulset","msg":"Reconciler error","reconciler group":"apps","reconciler kind":"StatefulSet","name":"alertmanager-alertmanager","namespace":"prod","error":"getting secret by name: prod/harbor: Secret \"harbor\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
E0823 05:50:12.339052       1 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 437 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16b6e20, 0xc001140ba0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
....
```
The resources that it tries to find, secret/harbor in the prod namespace, does not exist and I have no idea why it would try to find it either.

**To Reproduce**
1. Go to install starbord
2. Maybe observe the behavior.

**Expected behavior**
Starboard does not try to find a secret that does not exist.
Starboard does not accouter

 a panic causing it to crashloop indefinitely.

**Screenshots**
![Screenshot from 2021-08-23 08-02-20](https://user-images.githubusercontent.com/12396964/130398067-5d662bc5-346b-4cf3-be59-0109c9fe56cb.png)

**Version (add all relevant versions):**
v0.17.0

**Additional context**
I did try to remove all vulnerability reports and reinstall the operator. Didn't work as i still encouter a not being able to find a resource problem.

**Comment by OlleLarsson** [comment]
Closing as i have not encountered this error in some time now
