### ISSUE TITLE
Starboard: Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#579]
**Describe the bug**
Starboard operator crashlooping in service cluster.

```
{"level":"info","ts":1629790324.78894,"logger":"controller-runtime.manager.controller.job","msg":"Starting workers","reconciler group":"batch","reconciler kind":"Job","worker count":1}
E0824 07:32:04.833468       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 395 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15e4da0, 0x22e4a50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc000342e10, 0x19868d8, 0xc0011db500, 0xc0013a8000, 0xc001362b98, 0x4, 0xe, 0xc000607099, 0x3, 0xc0006070b0)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc000143440, 0x19868d8, 0xc0011db500, 0xc0013a8000, 0xa, 0xc000682450)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc0011db500, 0xc000607080, 0xa, 0xc000682450, 0x23, 0x16ad340, 0xc0011db500, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc000343650, 0x19868d8, 0xc0011db500, 0xc000607080, 0xa, 0xc000682450, 0x23, 0xc0011db500, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002748c0, 0x1986830, 0xc0001700c0, 0x1637940, 0xc000b394c0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002748c0, 0x1986830, 0xc0001700c0, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc0001700c0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00008a750)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002295f50, 0x1958280, 0xc0011db4a0, 0xc000170001, 0xc000148240)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00008a750, 0x3b9aca00, 0x0, 0xc000936a01, 0xc000148240)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc0001700c0, 0xc001189210, 0x3b9aca00, 0x0, 0x183ec01)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc0001700c0, 0xc001189210, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13a2505]

goroutine 395 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc000342e10, 0x19868d8, 0xc0011db500, 0xc0013a8000, 0xc001362b98, 0x4, 0xe, 0xc000607099, 0x3, 0xc0006070b0)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc000143440, 0x19868d8, 0xc0011db500, 0xc0013a8000, 0xa, 0xc000682450)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc0011db500, 0xc000607080, 0xa, 0xc000682450, 0x23, 0x16ad340, 0xc0011db500, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc000343650, 0x19868d8, 0xc0011db500, 0xc000607080, 0xa, 0xc000682450, 0x23, 0xc0011db500, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002748c0, 0x1986830, 0xc0001700c0, 0x1637940, 0xc000b394c0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002748c0, 0x1986830, 0xc0001700c0, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc0001700c0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00008a750)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc002295f50, 0x1958280, 0xc0011db4a0, 0xc000170001, 0xc000148240)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00008a750, 0x3b9aca00, 0x0, 0xc000936a01, 0xc000148240)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc0001700c0, 0xc001189210, 0x3b9aca00, 0x0, 0x183ec01)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc0001700c0, 0xc001189210, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
```

**To Reproduce**
1. Install starboard operator
2. Maybe notice error

**Expected behavior**

**Screenshots**

**Version (add all relevant versions):**
v0.16.0

**Additional context**

**Comment by OlleLarsson** [comment]
Full Log
```
❯ sokctl -n monitoring logs starboard-operator-845c46db7-nsw72
{"level":"info","ts":1629790502.9144459,"logger":"main","msg":"Starting operator","buildInfo":{"Version":"0.10.1","Commit":"21e893cb41c75144f9877735303bbf783c3f80bc","Date":"2021-04-21T19:48:38Z","Executable":""}}
{"level":"info","ts":1629790502.9151711,"logger":"operator","msg":"Resolved install mode","install mode":"AllNamespaces","operator namespace":"monitoring","target namespaces":[]}
{"level":"info","ts":1629790502.9158082,"logger":"operator","msg":"Watching all namespaces"}
I0824 07:35:03.969914       1 request.go:645] Throttling request took 1.034564169s, request: GET:https://10.96.0.1:443/apis/monitoring.coreos.com/v1alpha1?timeout=32s
{"level":"info","ts":1629790504.1242743,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1629790504.2571225,"logger":"operator","msg":"Starting controllers manager"}
{"level":"info","ts":1629790504.2574904,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1629790504.2577283,"logger":"controller-runtime.manager.controller.pod","msg":"Starting EventSource","reconciler group":"","reconciler kind":"Pod","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.258035,"logger":"controller-runtime.manager.controller.replicaset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"ReplicaSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.2582946,"logger":"controller-runtime.manager.controller.replicationcontroller","msg":"Starting EventSource","reconciler group":"","reconciler kind":"ReplicationController","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.2584515,"logger":"controller-runtime.manager.controller.statefulset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"StatefulSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.258666,"logger":"controller-runtime.manager.controller.daemonset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"DaemonSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.258878,"logger":"controller-runtime.manager.controller.cronjob","msg":"Starting EventSource","reconciler group":"batch","reconciler kind":"CronJob","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.2590027,"logger":"controller-runtime.manager.controller.job","msg":"Starting EventSource","reconciler group":"batch","reconciler kind":"Job","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.2592008,"logger":"controller-runtime.manager.controller.job","msg":"Starting EventSource","reconciler group":"batch","reconciler kind":"Job","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.358832,"logger":"controller-runtime.manager.controller.replicationcontroller","msg":"Starting EventSource","reconciler group":"","reconciler kind":"ReplicationController","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.3590984,"logger":"controller-runtime.manager.controller.pod","msg":"Starting EventSource","reconciler group":"","reconciler kind":"Pod","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.359313,"logger":"controller-runtime.manager.controller.replicaset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"ReplicaSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.359531,"logger":"controller-runtime.manager.controller.job","msg":"Starting Controller","reconciler group":"batch","reconciler kind":"Job"}
{"level":"info","ts":1629790504.3588345,"logger":"controller-runtime.manager.controller.statefulset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"StatefulSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.3595598,"logger":"controller-runtime.manager.controller.daemonset","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"DaemonSet","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.3595915,"logger":"controller-runtime.manager.controller.cronjob","msg":"Starting EventSource","reconciler group":"batch","reconciler kind":"CronJob","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.3596883,"logger":"controller-runtime.manager.controller.job","msg":"Starting EventSource","reconciler group":"batch","reconciler kind":"Job","source":"kind source: /, Kind="}
{"level":"info","ts":1629790504.5608222,"logger":"controller-runtime.manager.controller.cronjob","msg":"Starting Controller","reconciler group":"batch","reconciler kind":"CronJob"}
{"level":"info","ts":1629790504.5609388,"logger":"controller-runtime.manager.controller.cronjob","msg":"Starting workers","reconciler group":"batch","reconciler kind":"CronJob","worker count":1}
{"level":"info","ts":1629790504.5612557,"logger":"controller-runtime.manager.controller.replicationcontroller","msg":"Starting Controller","reconciler group":"","reconciler kind":"ReplicationController"}
{"level":"info","ts":1629790504.5613558,"logger":"controller-runtime.manager.controller.replicationcontroller","msg":"Starting workers","reconciler group":"","reconciler kind":"ReplicationController","worker count":1}
{"level":"info","ts":1629790504.5615878,"logger":"controller-runtime.manager.controller.replicaset","msg":"Starting Controller","reconciler group":"apps","reconciler kind":"ReplicaSet"}
{"level":"info","ts":1629790504.5616016,"logger":"controller-runtime.manager.controller.replicaset","msg":"Starting workers","reconciler group":"apps","reconciler kind":"ReplicaSet","worker count":1}
{"level":"info","ts":1629790504.5655894,"logger":"controller-runtime.manager.controller.job","msg":"Starting Controller","reconciler group":"batch","reconciler kind":"Job"}
{"level":"info","ts":1629790504.565684,"logger":"controller-runtime.manager.controller.job","msg":"Starting workers","reconciler group":"batch","reconciler kind":"Job","worker count":1}
{"level":"info","ts":1629790504.5701675,"logger":"controller-runtime.manager.controller.daemonset","msg":"Starting Controller","reconciler group":"apps","reconciler kind":"DaemonSet"}
{"level":"info","ts":1629790504.5703683,"logger":"controller-runtime.manager.controller.daemonset","msg":"Starting workers","reconciler group":"apps","reconciler kind":"DaemonSet","worker count":1}
{"level":"info","ts":1629790504.5723705,"logger":"controller-runtime.manager.controller.pod","msg":"Starting Controller","reconciler group":"","reconciler kind":"Pod"}
{"level":"info","ts":1629790504.5723934,"logger":"controller-runtime.manager.controller.pod","msg":"Starting workers","reconciler group":"","reconciler kind":"Pod","worker count":1}
{"level":"info","ts":1629790504.593973,"logger":"controller-runtime.manager.controller.statefulset","msg":"Starting Controller","reconciler group":"apps","reconciler kind":"StatefulSet"}
{"level":"info","ts":1629790504.5940654,"logger":"controller-runtime.manager.controller.statefulset","msg":"Starting workers","reconciler group":"apps","reconciler kind":"StatefulSet","worker count":1}
{"level":"info","ts":1629790504.6001377,"logger":"controller-runtime.manager.controller.job","msg":"Starting workers","reconciler group":"batch","reconciler kind":"Job","worker count":1}
E0824 07:35:04.622821       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 402 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15e4da0, 0x22e4a50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc00003bb40, 0x19868d8, 0xc001ca4ff0, 0xc001aded80, 0xc000b4fb30, 0x4, 0xe, 0xc00026df29, 0x3, 0xc00026df40)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc0001417a0, 0x19868d8, 0xc001ca4ff0, 0xc001aded80, 0xa, 0xc000041c50)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc001ca4ff0, 0xc00026df10, 0xa, 0xc000041c50, 0x22, 0x16ad340, 0xc001ca4ff0, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc00009b3f0, 0x19868d8, 0xc001ca4ff0, 0xc00026df10, 0xa, 0xc000041c50, 0x22, 0xc001ca4ff0, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002f25a0, 0x1986830, 0xc000568980, 0x1637940, 0xc000ac8b80)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002f25a0, 0x1986830, 0xc000568980, 0xc00055de00)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc000568980)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055df50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001587f50, 0x1958280, 0xc001ca4f90, 0xc000568901, 0xc00007e1e0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055df50, 0x3b9aca00, 0x0, 0x1271e01, 0xc00007e1e0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc000568980, 0xc0006331a0, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc000568980, 0xc0006331a0, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13a2505]

goroutine 402 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc00003bb40, 0x19868d8, 0xc001ca4ff0, 0xc001aded80, 0xc000b4fb30, 0x4, 0xe, 0xc00026df29, 0x3, 0xc00026df40)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc0001417a0, 0x19868d8, 0xc001ca4ff0, 0xc001aded80, 0xa, 0xc000041c50)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc001ca4ff0, 0xc00026df10, 0xa, 0xc000041c50, 0x22, 0x16ad340, 0xc001ca4ff0, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc00009b3f0, 0x19868d8, 0xc001ca4ff0, 0xc00026df10, 0xa, 0xc000041c50, 0x22, 0xc001ca4ff0, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002f25a0, 0x1986830, 0xc000568980, 0x1637940, 0xc000ac8b80)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002f25a0, 0x1986830, 0xc000568980, 0xc00055de00)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc000568980)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00055df50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001587f50, 0x1958280, 0xc001ca4f90, 0xc000568901, 0xc00007e1e0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00055df50, 0x3b9aca00, 0x0, 0x1271e01, 0xc00007e1e0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc000568980, 0xc0006331a0, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc000568980, 0xc0006331a0, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
```

**Comment by Xartos** [comment]
Seems to be related to [this issue](https://github.com/aquasecurity/starboard/issues/627). So we should upgrade to v0.12.0
