### ISSUE TITLE
Starboard: crashed due to too long resource names(?)

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#583]
**Describe the bug**
Starboard operator is crashlooping with
```
{"level":"error","ts":1629881820.5973485,"logger":"controller-runtime.manager.controller.replicaset","msg":"Reconciler error","reconciler group":"apps","reconciler kind":"ReplicaSet","name":"rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94","namespace":"rook-ceph","error":"creating job: Job.batch \"scan-vulnerabilityreport-b6dc7557c\" is invalid: [metadata.labels: Invalid value: \"rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94\": must be no more than 63 characters, spec.template.labels: Invalid value: \"rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94\": must be no more than 63 characters]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
E0825 08:57:00.696914       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 407 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x15e4da0, 0x22e4a50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc00048f4e0, 0x19868d8, 0xc001d3e810, 0xc001d40900, 0xc001ccb510, 0xa, 0x18, 0xc0000acc60, 0xd, 0xc0000acc40)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc00042c6c0, 0x19868d8, 0xc001d3e810, 0xc001d40900, 0xa, 0xc000041bf0)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc001d3e810, 0xc0000acc10, 0xa, 0xc000041bf0, 0x23, 0x16ad340, 0xc001d3e810, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc00048fca0, 0x19868d8, 0xc001d3e810, 0xc0000acc10, 0xa, 0xc000041bf0, 0x23, 0xc001d3e810, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002125a0, 0x1986830, 0xc00065e240, 0x1637940, 0xc000850040)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002125a0, 0x1986830, 0xc00065e240, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc00065e240)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000591750)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001febf50, 0x1958280, 0xc001d026f0, 0xc00065e201, 0xc0000882a0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000591750, 0x3b9aca00, 0x0, 0x1, 0xc0000882a0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc00065e240, 0xc001d04380, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc00065e240, 0xc001d04380, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13a2505]

goroutine 407 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x15e4da0, 0x22e4a50)
	/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/panic.go:965 +0x1b9
github.com/aquasecurity/starboard/pkg/kube.(*logsReader).GetLogsByJobAndContainerName(0xc00048f4e0, 0x19868d8, 0xc001d3e810, 0xc001d40900, 0xc001ccb510, 0xa, 0x18, 0xc0000acc60, 0xd, 0xc0000acc40)
	/home/runner/work/starboard/starboard/pkg/kube/logs.go:35 +0x1e5
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).processCompleteScanJob(0xc00042c6c0, 0x19868d8, 0xc001d3e810, 0xc001d40900, 0xa, 0xc000041bf0)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:375 +0xb28
github.com/aquasecurity/starboard/pkg/operator/controller.(*VulnerabilityReportReconciler).reconcileJobs.func1(0x19868d8, 0xc001d3e810, 0xc0000acc10, 0xa, 0xc000041bf0, 0x23, 0x16ad340, 0xc001d3e810, 0x15e33c0, 0x23351c8)
	/home/runner/work/starboard/starboard/pkg/operator/controller/vulnerabilityreport.go:323 +0x31b
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc00048fca0, 0x19868d8, 0xc001d3e810, 0xc0000acc10, 0xa, 0xc000041bf0, 0x23, 0xc001d3e810, 0xc000030000, 0x166e740, ...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002125a0, 0x1986830, 0xc00065e240, 0x1637940, 0xc000850040)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:263 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002125a0, 0x1986830, 0xc00065e240, 0x0)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1986830, 0xc00065e240)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000591750)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001febf50, 0x1958280, 0xc001d026f0, 0xc00065e201, 0xc0000882a0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000591750, 0x3b9aca00, 0x0, 0x1, 0xc0000882a0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1986830, 0xc00065e240, 0xc001d04380, 0x3b9aca00, 0x0, 0x1)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1986830, 0xc00065e240, 0xc001d04380, 0x3b9aca00)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:195 +0x497
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version [e.g. v0.8.0]

**Additional context**

**Comment by robinAwallace** [comment]
The first line of your crachloop log unsquashed is:
```
{
    "level": "error",
    "ts": 1629881820.5973485,
    "logger": "controller-runtime.manager.controller.replicaset",
    "msg": "Reconciler error",
    "reconciler group": "apps",
    "reconciler kind": "ReplicaSet",
    "name": "rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94",
    "namespace": "rook-ceph",
    "error": "creating job: Job.batch \"scan-vulnerabilityreport-b6dc7557c\" is invalid: [metadata.labels: Invalid value: \"rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94\": must be no more than 63 characters, spec.template.labels: Invalid value: \"rook-ceph-crashcollector-<removed>-sc-cluster-k8s-node-b-xlarge-1-8487676d94\": must be no more than 63 characters]",
    "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"
}
```
Indicating that a rook-ceph had a name greater then 63 characters which interfered with starboard. Unsure how to fix such a problem. Any ideas?

**Comment by robinAwallace** [comment]
Seems like it is a known issue: https://github.com/aquasecurity/starboard/issues/288

**Comment by OlleLarsson** [comment]
Okay!
Not very promising that they haven't solved it yet considering that it's almost been 9 months since the issue was created 😞
